fixed camera example
bottlepay/plugins pull request #1
Opened 2021-03-03 01:37 UTC by nt4f04uNd

2021-03-23 15:08 UTC, nt4f04uNd commented
@acoutts can you review this?

2021-03-23 16:08 UTC, acoutts commented
Sorry i've bene totally slammed, hoping to get to reviewing this later in the week.

2021-03-24 20:29 UTC, mvanbeusekom requested changes
Hi @nt4f04uNd, 

Could you submit this PR directly on the flutter/plugins repo? The pull request with the Android changes is already (too) large and reviewers are requesting us for finding ways to split it up into separate PRs. Adding these changes would only add to the collection of changed lines. Also your fixes for the example App would also add a lot of benefit while these changes are not yet merged in the main repo.

Besides that I added some addition questions / remarks to this PR which could maybe also taking into consideration when creating a separate PR.

2021-03-24 20:29 UTC, mvanbeusekom commented on packages/camera/camera/example/lib/main.dart
> +    final CameraController _controller = CameraController(
What would be the reason to rename this variable from `cameraController` to `_controller`? The original name was more descriptive and the added `_` would suggest it concerns a private class level field which is not the case.

2021-03-24 20:29 UTC, mvanbeusekom commented on packages/camera/camera/example/lib/main.dart
> +    final _videoController = VideoPlayerController.file(File(videoFile!.path));
Although the name is more semantic here, the `_` suggests the variable is a private class level field. The variable is a local method scope. Not sure if the semantic gains outweighs the scope. But maybe we can rename it something like `localVideoController`?

2021-03-24 21:44 UTC, nt4f04uNd commented on packages/camera/camera/example/lib/main.dart
> -      throw ArgumentError('Unknown lens direction');
some lint from nnbd was telling me about it
totally agree, will add it back

2021-03-24 21:46 UTC, nt4f04uNd commented on packages/camera/camera/example/lib/main.dart
> +    final _videoController = VideoPlayerController.file(File(videoFile!.path));
yes, makes sense

2021-03-24 21:48 UTC, nt4f04uNd commented on packages/camera/camera/example/lib/main.dart
> +    final CameraController _controller = CameraController(
i renamed it to match the instance name `controller`, `_` was added to not overlap with it. `localController` better suits i guess

2021-03-24 21:49 UTC, nt4f04uNd commented
i thought the progress on the original PR would be a little bit faster, but now i totally agree that i should make this as a separate PR

thanks for your comments, i will address them

2021-03-24 21:49 UTC, closed without merging